[package]
name = "ixy-net"
version = "0.1.0"
authors = ["HeroicKatora <andreas.molzer@gmx.de>"]
edition = "2018"

[dependencies]
ixy = { path = "ixy.rs" }
ethox = { path = "ethox/ethox", features = ["std"] }

[dev-dependencies]
env_logger = "0.6"
structopt = "0.2"
