[package]
name = "ixy-net"
version = "0.1.0"
authors = ["HeroicKatora <andreas.molzer@gmx.de>"]
edition = "2018"

[dependencies]
ixy = { path = "ixy.rs" }
smoltcp = "0.5"

[dev-dependencies]
env_logger = "0.6"
